### ISSUE TITLE
Accessing the 340 webpage for code review 

### ISSUE THREAD

**Issue by LloydProductions** [Montana-Media-Arts/191_CreativeCoding#2]
There was a webpage we were asked to access for the 340 class with multiple drop downs. I am having trouble finding that page with the examples of the code on it. I'm not quite sure how to get to it so if someone could send me in the right direction or could share the link to it, I would appreciate it greatly.

**Comment by LloydProductions** [comment]
Never mind, I was able to figure it out

**Comment by michaelmusick** [comment]
Thanks for the follow up @LloydProductions
